### ISSUE TITLE
OverflowError: long int too large to convert to int

### ISSUE THREAD

**Issue by WangLei-UESTC** [yuanyuanli85/CaffeModelCompression#7]
thanks for your code ,but when i run the code ,i got this error:
Traceback (most recent call last):
  File "caffemodel_compress.py", line 96, in <module>
    caffe_model_compress(netmodel, netweights, output, 6, 2)
  File "caffemodel_compress.py", line 20, in caffe_model_compress
    for item in net.params.items():
  File "/home/wl/caffe/python/caffe/pycaffe.py", line 68, in _Net_params
    if len(lr.blobs) > 0])
OverflowError: long int too large to convert to int
help me please!

**Comment by vidit09** [comment]
see the issue here. https://github.com/BVLC/caffe/issues/2437   .. Works for me.
